### ISSUE TITLE
What exactly is in https://github.com/dcsoft-yyf/DCNETProtector/blob/main/source/DCNETProtector.csproj ?

### ISSUE THREAD

**Issue by hakakou** [dcsoft-yyf/JIEJIE.NET#1]
This should be a csproj, readable xml file, but instead I see a binary file with this:

![image](https://user-images.githubusercontent.com/10587642/119194894-6f465480-ba8c-11eb-9489-d689aa2bda75.png)

**Comment by dcsoft-yyf** [comment]
thank you. I fixed it.&nbsp;



---Original---
From: "Harry ***@***.***&gt;
Date: Fri, May 21, 2021 13:31 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [dcsoft-yyf/DCNETProtector] What exactly is in https://github.com/dcsoft-yyf/DCNETProtector/blob/main/source/DCNETProtector.csproj ? (#1)




 
This should be a csproj, readable xml file, but instead I see a binary file with this:
