### ISSUE TITLE
编译不通过

### ISSUE THREAD

**Issue by tabs** [dcsoft-yyf/JIEJIE.NET#12]
已启动生成...
1>------ 已启动生成: 项目: BitMono.GUI, 配置: Debug Any CPU ------
未能还原 E:\source\BitMono\test\BitMono.Obfuscation.Tests\BitMono.Obfuscation.Tests.csproj (用时 92 ms)。
NuGet 包还原失败。请查看“错误列表”窗口了解详细警告和错误。
1>D:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(1830,5): warning NU1702: 已使用“.NETFramework,Version=v4.6.2”而不是项目目标框架“.NETCoreApp,Version=v7.0”解析 ProjectReference“E:\source\BitMono\src\BitMono.Core\BitMono.Core.csproj”。此项目可能与你的项目不完全兼容。
1>MSBUILD : error MSB4166: 子节点“2”过早退出。正在关闭。可以在“C:\Users\changyaqiang\AppData\Local\Temp\MSBuildTempchangyaqiang\”中的文件中找到诊断信息，并将其命名为 MSBuild_*.failure.txt。通过将 MSBUILDDEBUGPATH 环境变量设为其他目录，可更改此位置。

**Comment by dcsoft-yyf** [comment]
删除 bin和obj目录就行了。
