### ISSUE TITLE
 远程处理无法在类型“JIEJIE.DCJieJieNetEngine”上找到字段“_UseAnotherExeName”

### ISSUE THREAD

**Issue by rsdte** [dcsoft-yyf/JIEJIE.NET#4]
我用 1.3 版本的 jiejie 软件来混淆/加密我的程序集，在使用时报了` 远程处理无法在类型“JIEJIE.DCJieJieNetEngine”上找到字段“_UseAnotherExeName”`错误。

当前环境
    系统版本：win11 21H2
    .net sdk：dotnet core 3.1

使用信息：
```shell
.\JIEJIE.NET.exe input=F:\Release\core\jiejie\CaliburnCore.dll output=F:\Release\core\jiejie\res\CaliburnCore1.dll switch=+controlflow,+string,+resources,+memberorder,+rename,+allocationcallstack,+removemember
```

更多报错信息：
![image](https://user-images.githubusercontent.com/39526920/147810640-85423f5b-231a-443c-9f7a-a2161bb9ff35.png)

**Comment by dcsoft-yyf** [comment]
1.3是比较旧的版本了。你先使用最新的源代码编译试试看。

**Comment by dcsoft-yyf** [comment]
use v1.2022.1.6
