### ISSUE TITLE
my anti virus trait it as a trojan 

### ISSUE THREAD

**Issue by muhamedRadwan** [dcsoft-yyf/JIEJIE.NET#6]
My anti-virus delete the zip file because it have a trojan

**Comment by dcsoft-yyf** [comment]
Maby because JIEJIE.NET create dll/exe file. JIEJIE.NET is open source , it is safe.

**Comment by dcsoft-yyf** [comment]
You can download source file and open JIJIE.NET project use VS.NET and build a exe by youself.
